name: CD

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Cache MinGW
      id: cache-mingw
      uses: actions/cache@v4.0.2
      with:
        path: C:\tools\mingw64
        key: ${{ runner.os }}-mingw
        restore-keys: |
          ${{ runner.os }}-mingw
          
    - name: Install MinGW
      if: steps.cache-mingw.outputs.cache-hit != 'true'
      run: |
        mkdir -p C:\tools\mingw64  # Create MinGW directory if not exists
        choco install mingw --params "/NoPath /InstallationPath:C:\tools\mingw64" -y
        echo "C:\tools\mingw64\bin" >> $GITHUB_PATH

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
          version: '6.7.0'
          cache: 'true'
          host: 'windows'
          dir: '${{github.workspace}}/Qt/'
          install-deps: 'true'

    - name: Verify Qt installation
      run: |
        dir "${{github.workspace}}/Qt/6.7.0/mingw_64"
        dir "${{github.workspace}}/Qt/6.7.0/mingw_64/include"
        dir "${{github.workspace}}/Qt/6.7.0/mingw_64/lib"
        dir "${{github.workspace}}/Qt/6.7.0/mingw_64/bin"

    - name: Set up Qt environment
      run: |
        echo "${{github.workspace}}/Qt/6.7.0/mingw_64/bin" >> $GITHUB_PATH
        echo "INCLUDE=${{github.workspace}}/Qt/6.7.0/mingw_64/include" >> $GITHUB_ENV
        echo "LIB=${{github.workspace}}/Qt/6.7.0/mingw_64/lib" >> $GITHUB_ENV

    - name: Build using MinGW
      run: |
        g++ -I"${{github.workspace}}/Qt/6.7.0/mingw_64/include" -I"${{github.workspace}}/Qt/6.7.0/mingw_64/include/QtWidgets" -I"${{github.workspace}}/Qt/6.7.0/mingw_64/include/QtCore" -I"${{github.workspace}}/Qt/6.7.0/mingw_64/include/QtGui" -L"${{github.workspace}}/Qt/6.7.0/mingw_64/lib" GUI_Tic_Tac_Toe/main.cpp -o Advanced-Tic-Tac-Toe.exe -lQt6Widgets -lQt6Core -lQt6Gui

    - name: Deploy executable
      run: |
        mkdir -p $GITHUB_WORKSPACE/deploy/
        cp Advanced-Tic-Tac-Toe.exe $GITHUB_WORKSPACE/deploy/

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: my-executable
        path: $GITHUB_WORKSPACE/deploy/Advanced-Tic-Tac-Toe.exe
