name: CD

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        aqtversion: '==3.1.*'
        version: '6.7.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        tools: 'tools_mingw90'

    - name: Verify Qt installation
      run: |
        dir "D:/a/Advanced-Tic-Tac-Toe/Qt/6.7.0/mingw_64/"
        dir "D:/a/Advanced-Tic-Tac-Toe/Qt/6.7.0/mingw_64/include"
        dir "D:/a/Advanced-Tic-Tac-Toe/Qt/6.7.0/mingw_64/lib"
        dir "D:/a/Advanced-Tic-Tac-Toe/Qt/6.7.0/mingw_64/bin"

    - name: Set up Qt environment
      run: |
        echo "D:/a/Advanced-Tic-Tac-Toe/Qt/6.7.0/mingw_64/bin" >> $GITHUB_PATH
        echo "INCLUDE=D:/a/Advanced-Tic-Tac-Toe/Qt/6.7.0/mingw_64/include" >> $GITHUB_ENV
        echo "LIB=D:/a/Advanced-Tic-Tac-Toe/Qt/6.7.0/mingw_64/lib" >> $GITHUB_ENV

    - name: Build using MinGW
      run: |
        g++ -I"D:/a/Advanced-Tic-Tac-Toe/Qt/6.7.0/mingw_64/include" -L"D:/a/Advanced-Tic-Tac-Toe/Qt/6.7.0/mingw_64/lib" GUI_Tic_Tac_Toe/main.cpp -o Advanced-Tic-Tac-Toe.exe

    - name: Deploy executable
      run: |
        mkdir -p $GITHUB_WORKSPACE/deploy/
        cp Advanced-Tic-Tac-Toe.exe $GITHUB_WORKSPACE/deploy/

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: my-executable
        path: $GITHUB_WORKSPACE/deploy/Advanced-Tic-Tac-Toe.exe
