name: Build Qt Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4.0.0
      with:
        version: '5.15.2'  # Specify the Qt version you need
        host: 'windows'
        modules: qtbase, qttools

    - name: Install dependencies
      run: choco install -y ninja

    - name: Configure and build the project
      run: |
        mkdir build
        cd build
        qmake ../your_project.pro
        nmake

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/
