name: Build Qt Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
    
    - name: Set up Qt
      uses: jurplel/install-qt-action@v4

    - name: Install dependencies
      run: |
        choco install -y ninja
        choco install -y qtcreator  # Install Qt Creator for additional tools
        choco install -y make
        choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'  # Install CMake and add it to PATH

    - name: Configure and build the project
      run: |
        mkdir build
        cd build
        qmake ../Advanced-Tic-Tac-Toe.pro
        make

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/
