name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MinGW
      run: |
        choco install mingw -y
        echo "C:\tools\mingw64\bin" >> $GITHUB_PATH

    - name: Build using MinGW
      run: |
        g++ -Igoogletest/googletest/include -Igoogletest/googlemock/include -o test_tic_tac_toe.exe tests/test_tic_tac_toe.cpp googletest/googletest/src/gtest-all.cc googletest/googlemock/src/gmock-all.cc -pthread

    - name: Run tests
      run: .\test_tic_tac_toe.exe
