name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Cache MinGW
      id: cache-mingw
      uses: actions/cache@v4.0.2
      with:
        path: C:\tools\mingw64
        key: ${{ runner.os }}-mingw
        restore-keys: |
          ${{ runner.os }}-mingw
          
    - name: Install MinGW
      if: steps.cache-mingw.outputs.cache-hit != 'true'
      run: |
        mkdir -p C:\tools\mingw64  # Create MinGW directory if not exists
        choco install mingw --params "/NoPath /InstallationPath:C:\tools\mingw64" -y
        echo "C:\tools\mingw64\bin" >> $GITHUB_PATH

    - name: Cache Google Test
      id: cache-gtest
      uses: actions/cache@v4.0.2
      with:
        path: GUI_Tic_Tac_Toe/googletest/build
        key: ${{ runner.os }}-gtest
        restore-keys: |
          ${{ runner.os }}-gtest

    - name: Build Google Test
      if: steps.cache-gtest.outputs.cache-hit != 'true'
      run: |
        cd GUI_Tic_Tac_Toe/googletest
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" ..
        mingw32-make
        cd ../..
          
    - name: Build using MinGW
      run: |
        g++ -IGUI_Tic_Tac_Toe/googletest/googletest/include -IGUI_Tic_Tac_Toe/googletest/googlemock/include -LGUI_Tic_Tac_Toe/googletest/build/lib GUI_Tic_Tac_Toe/tests/test_tic_tac_toe.cpp -lgmock -lgtest -lgmock_main -lgtest_main -o test_tic_tac_toe.exe -pthread

    - name: Run tests
      run: .\test_tic_tac_toe.exe
