name: CI_LINUX

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake make libgtest-dev

    - name: Build Google Test
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib

    - name: Build using g++
      run: |
        mkdir -p build
        g++ -I/usr/include -Igoogletest/googletest/include -Igoogletest/googlemock/include -L/usr/lib -L/usr/local/lib tests/test_tic_tac_toe.cpp -lgtest -lgtest_main -lpthread -o build/test_tic_tac_toe

    - name: Run tests
      run: ./build/test_tic_tac_toe
