name: CI_LINUX

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake make

    - name: Build Google Test
      run: |
        cd googletest
        mkdir -p build
        cd build
        cmake ..
        make
        cd ../..

    - name: Build using g++
      run: |
        g++ -Igoogletest/googletest/include -Igoogletest/googlemock/include -Lgoogletest/build/googlemock -Lgoogletest/build/googlemock/gtest tests/test_tic_tac_toe.cpp -lgmock -lgtest -lgmock_main -lgtest_main -o build/test_tic_tac_toe -pthread

    - name: Run tests
      run: ./build/test_tic_tac_toe
