name: Deploy Tic Tac Toe Game

on:
  push:
    branches:
      - main

env:
  SOLUTION_FILE_PATH: ..  # Path to your solution file relative to the project root
  BUILD_CONFIGURATION: Release  # Configuration type to build (e.g., Debug or Release)
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Qt environment
      uses: jurplel/install-qt-action@v4
      with:
        qt-version: '6.7'
        cache : true
        host: windows
        target: desktop
        arch: win64_msvc2019_64
        dir: ${{ runner.temp }}

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Create build folder
      run: mkdir -p ${{ runner.temp }}\\build
    - name: Build with MSBuild
      working-directory: ${{ runner.temp }}\\build
      run: |
        echo "Start building in ${{ runner.temp }}\\build"
        cd ${{ runner.temp }}\\build
        msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} ${{ github.workspace }}\\xxx.sln
