name: Build and Deploy Qt Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.4.3
          target: desktop
          arch: linux

      - name: Configure project
        run: qmake Advanced-Tic-Tac-Toe.pro

      - name: Build project
        run: make

      # Add deployment steps here (e.g., deploying artifacts)

